"""Added initial tables

Revision ID: abb5963b1c99
Revises: 
Create Date: 2022-02-27 21:59:48.528801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb5963b1c99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('admin', sa.String(length=128), nullable=True),
    sa.Column('chat_type', sa.Enum('private', 'group', 'supergroup', 'channel', name='chattype'), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_chat_chat_id'))
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.String(length=128), nullable=True),
    sa.Column('next_question_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['next_question_id'], ['question.id'], name=op.f('fk_question_next_question_id_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    op.create_table('hint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_hint_question_id_question')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hint'))
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('media', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['chat'], ['chat.id'], name=op.f('fk_message_chat_chat')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('hint')
    op.drop_table('question')
    op.drop_table('chat')
    # ### end Alembic commands ###
